- hosts: 127.0.0.1
  connection: local
  no_log: "{{ lookup('ansible.builtin.env', 'MEGAPOLOS_DEBUG') == '0' }}"
  vars: 
    name: "megapolos"
    compose_file: /opt/megapolos_swarm_compose.yml
    data: "{{ lookup('file',lookup('ansible.builtin.env', 'JSON_PATH')) }}"
  tasks:
  # - ansible.builtin.pip:
  #     name: 
  #       - jsondiff
  #     state: present
  - name: volume directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    with_items: "{{ data.volumes }}"
  - name: Copy stack file
    template:
        src: swarm_compose.yml
        dest: "{{ compose_file }}"
        mode: 0444
    register: stack_file
    tags: stack
  - name: start swarm
    community.docker.docker_swarm:
      state: present
  - name: Deploy stack
    docker_stack:
        state: present
        name: "{{ name }}"
        prune: yes
        with_registry_auth: yes
        compose:
        - "{{ compose_file }}"
