- hosts: "{{ hosts }}"
  vars: 
    name: "megapolos"
    compose_file: /opt/megapolos_swarm_compose.yml
    data: "{{ lookup('file',lookup('ansible.builtin.env', 'JSON_PATH')) }}"
  tasks:
  - name: swarm directory
    ansible.builtin.file:
      path: /opt/megapolos_swarm_compose
      state: directory
  - name: nginx directory
    ansible.builtin.file:
      path: /data/nginx/conf
      state: directory
  - name: certbot cron
    ansible.builtin.cron:
      name: "certbot cron"
      minute: "0"
      hour: "3"
      job: "certbot renew --quiet --pre-hook \"docker stop nginx\" --post-hook \"docker start nginx\""
  - name: volume directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    with_items: "{{ data.volumes }}"
  - name: Install pip
    ansible.builtin.apt:
      name: pip
      state: present
  - name: Install packages
    ansible.builtin.pip:
      name: 
        - jsondiff 
        - docker
        - passlib
  - name: Copy nginx conf file
    template:
      src: nginx.conf.template
      dest: /data/nginx/nginx.conf
  - name: nginx
    community.docker.docker_container:
      name: nginx
      image: nginx
      ports:
        - "80:80"
        - "443:443"
        - "5102:5102"
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /data/nginx/conf:/etc/nginx/conf.d
        - /var/run/docker.sock:/var/run/docker.sock
        - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
  - name: docker access
    community.docker.docker_container_exec:
      container: nginx
      command: "chmod -v 0777 /var/run/docker.sock"
  - name: docker password
    community.general.htpasswd:
      path: /data/nginx/conf/docker.htpasswd
      name: megapolos
      password: "{{ data.node.password }}"
  - name: openssl_privatekey
    openssl_privatekey:
      path: /data/nginx/conf/certificate.key
      size: 2048 
  - name: openssl_csr
    openssl_csr:
      path: /data/nginx/conf/certificate.csr
      privatekey_path: /data/nginx/conf/certificate.key
  - name: openssl_certificate
    openssl_certificate:
      provider: selfsigned
      path: /data/nginx/conf/certificate.crt
      privatekey_path: /data/nginx/conf/certificate.key
      csr_path: /data/nginx/conf/certificate.csr
  - name: Copy docker nginx conf
    template:
      src: nginx.docker.template
      dest: /data/nginx/conf/docker.conf
  - name: Log into private registry and force re-authorization
    docker_login:
        registry: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY') }}"
        username: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY_PASSWORD') }}"
        reauthorize: yes
  - name: Copy stack file
    template:
        src: swarm_compose.yml
        dest: "{{ compose_file }}"
        mode: 0444
    register: stack_file
    tags: stack
  - name: Pull images
    ansible.builtin.shell: docker-compose -f /opt/megapolos_swarm_compose.yml pull
  - name: Deploy stack
    docker_stack:
        state: present
        name: "{{ name }}"
        prune: yes
        with_registry_auth: yes
        compose:
        - "{{ compose_file }}"
  - ansible.builtin.pip:
      name: 
        - urllib3
      state: absent
  - name: certificate
    shell: |
      certbot certonly  --pre-hook "docker stop nginx || true" --post-hook "docker start nginx || true" --standalone --noninteractive --agree-tos --cert-name {{ item.domain_name }} -d {{ item.domain_name }} --register-unsafely-without-email
    args: 
      creates: /etc/letsencrypt/live/{{ item.domain_name }}/fullchain.pem
    with_items: "{{ data.containers }}"
    when: item.domain_name != None
  - name: Copy nginx virtualhosts conf
    template:
      src: nginx.vhost.template
      dest: /data/nginx/conf/{{ item.domain_name }}.conf
    with_items: "{{ data.containers }}"
    when: item.domain_name != None
  - name: ensure a nginx is running
    docker_container:
      name: nginx
      state: started
  - name: reload nginx
    community.docker.docker_container_exec:
      container: nginx
      command: nginx -s reload
