- hosts: all
  no_log: "{{ lookup('ansible.builtin.env', 'MEGAPOLOS_DEBUG') == '0' }}"
  vars: 
    name: "megapolos"
    compose_file: /opt/megapolos_swarm_compose.yml
    data: "{{ lookup('file',lookup('ansible.builtin.env', 'JSON_PATH')) }}"
  tasks:
  - name: init
    import_tasks: init_include.yml
    when: data.init is defined and data.init != None and data.init != False
  - name: volume directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    with_items: "{{ data.volumes }}"
  - name: Log into private registry and force re-authorization
    docker_login:
        registry: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY') }}"
        username: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY_PASSWORD') }}"
        reauthorize: yes
  - name: Copy stack file
    template:
        src: swarm_compose.yml
        dest: "{{ compose_file }}"
        mode: 0444
    register: stack_file
    tags: stack
  - name: Pull images
    ansible.builtin.shell: docker compose -f /opt/megapolos_swarm_compose.yml pull {{ item.name }}
    with_items: "{{ data.containers }}"
    when: 
      - (item.disabled is not defined or item.disabled == False)
      - (data.isPartialUpdate is not defined or data.isPartialUpdate != True) or (item.isUpdated is defined and item.isUpdated == True)
  - name: start swarm
    community.docker.docker_swarm:
      state: present
      task_history_retention_limit: 1
  - name: Deploy stack
    docker_stack:
        state: present
        name: "{{ name }}"
        prune: yes
        with_registry_auth: yes
        compose:
        - "{{ compose_file }}"
  - name: clear docker images
    shell: |
      docker image prune -a -f
  - ansible.builtin.pip:
      name: 
        - urllib3
      state: absent
  - name: certificate
    shell: |
      certbot certonly  --pre-hook "docker stop nginx || true" --post-hook "docker start nginx || true" --standalone --noninteractive --agree-tos --cert-name {{ item.domain_name }} -d {{ item.domain_name }} --register-unsafely-without-email
    args: 
      creates: /etc/letsencrypt/live/{{ item.domain_name }}/fullchain.pem
    with_items: "{{ data.containers }}"
    when: item.domain_name != None
  - ansible.builtin.pip:
      name: 
        - urllib3
      state: present
  - name: remove conf
    shell: |
      rm -f /data/nginx/conf/*.vhost.conf
  - name: Copy nginx virtualhosts conf
    template:
      src: nginx.vhost.template
      dest: /data/nginx/conf/{{ item.domain_name }}.vhost.conf
    with_items: "{{ data.containers }}"
    when: item.domain_name != None
  - name: domain password
    community.general.htpasswd:
      path: /data/nginx/conf/{{ item.domain_name }}.htpasswd
      name: "{{ item.auth_user }}"
      password: "{{ item.auth_password }}"
    with_items: "{{ data.containers }}"
    when: item.auth_user is defined
  - name: ensure a nginx is running
    docker_container:
      name: nginx
      state: started
  - name: reload nginx
    community.docker.docker_container_exec:
      container: nginx
      command: nginx -s reload
