- name: swarm directory
  ansible.builtin.file:
    path: /opt/megapolos_swarm_compose
    state: directory
- name: nginx directory
  ansible.builtin.file:
    path: /data/nginx/conf
    state: directory
- name: certbot cron
  ansible.builtin.cron:
    name: "certbot cron"
    minute: "0"
    hour: "3"
    job: "certbot renew --quiet --pre-hook \"docker stop nginx\" --post-hook \"docker start nginx\""
- name: Install pip
  ansible.builtin.apt:
    name: pip
    state: present
- name: Install packages
  ansible.builtin.pip:
    name: 
      - jsondiff 
      - docker
      - passlib
      - urllib3
- name: Install collection community.docker
  community.general.ansible_galaxy_install:
    type: collection
    name: community.docker
- name: Copy nginx conf file
  template:
    src: nginx.conf.template
    dest: /data/nginx/nginx.conf
- name: nginx
  community.docker.docker_container:
    name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5102:5102"
      - "5104:5104"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/nginx/conf:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
- name: docker access
  community.docker.docker_container_exec:
    container: nginx
    command: "chmod -v 0777 /var/run/docker.sock"
- name: docker password
  community.general.htpasswd:
    path: /data/nginx/conf/docker.htpasswd
    name: megapolos
    password: "{{ data.node.password }}"
# - name: openssl_privatekey
#   openssl_privatekey:
#     path: /data/nginx/conf/certificate.key
#     size: 2048 
# - name: openssl_csr
#   openssl_csr:
#     path: /data/nginx/conf/certificate.csr
#     privatekey_path: /data/nginx/conf/certificate.key
# - name: openssl_certificate
#   openssl_certificate:
#     provider: selfsigned
#     path: /data/nginx/conf/certificate.crt
#     privatekey_path: /data/nginx/conf/certificate.key
#     csr_path: /data/nginx/conf/certificate.csr
- name: certificate
  shell: |
    certbot certonly  --pre-hook "docker stop nginx || true" --post-hook "docker start nginx || true" --standalone --noninteractive --agree-tos --cert-name {{ data.node.host }} -d {{ data.node.host }} --register-unsafely-without-email
  args: 
    creates: /etc/letsencrypt/live/{{ data.node.host }}/fullchain.pem
- name: Copy docker nginx conf
  template:
    src: nginx.docker.template
    dest: /data/nginx/conf/docker.conf
- name: ensure a nginx is running
  docker_container:
    name: nginx
    state: started
- name: reload nginx
  community.docker.docker_container_exec:
    container: nginx
    command: nginx -s reload
