version: "3.7"
services:
{% for item in data.containers %}
{% if True or item.disabled is not defined and item.disabled != True %}
  {{ item.name }}:
    image: "{{ item.image }}"
{% if item.outer_port != None and item.inner_port != 0 and (data.dev_mode is not defined or data.dev_mode != True) %}
    ports: 
      - {{ item.outer_port }}:{{ item.inner_port | default(80) }}
{% endif %}
{% if item.outer_port != None and item.inner_port != 0 and data.dev_mode is defined and data.dev_mode == True %}
    ports: 
      - published: {{ item.outer_port }}
        target: {{ item.inner_port | default(80) }}
        protocol: tcp
        mode: host
{% endif %}
{% if item.envs is defined and item.envs|length>0 %}
    environment:
{% for env in item.envs %}
      - {{ env.name }}={{ env.value }}
{% endfor %}     
{% endif %} 
{% if item.volumes is defined and item.volumes|length>0 %}
    volumes:
{% for volume in item.volumes %}
      - {{ volume.source }}:{{ volume.target }}
{% endfor %}      
{% endif %}
    labels:
      megapolos_id: "{{ item.description }}"
    deploy:
      mode: replicated
{% if item.disabled is defined and item.disabled == True %}
      replicas: 0
{% else %}
      replicas: 1
{% endif %}
      labels:
        megapolos_id: "{{ item.description }}"
{% endif %}
{% endfor %}
