version: "3.7"
services:
{% for item in data.containers %}
{% if True or item.disabled is not defined and item.disabled != True %}
  {{ item.name }}:
    image: "{{ item.image }}"
{% if item.outer_port != None %}
    ports: 
      - {{ item.outer_port }}:{{ item.inner_port | default(80) }}
{% endif %}
    environment:
{% if item.envs is defined %}
{% for env in item.envs %}
      - {{ env.name }}={{ env.value }}
{% endfor %}     
{% endif %} 
    volumes:
{% if item.volumes is defined %}
{% for volume in item.volumes %}
      - {{ volume.source }}:{{ volume.target }}
{% endfor %}      
{% endif %}
    deploy:
      mode: replicated
      replicas: 1
{% endif %}
{% endfor %}
